### ISSUE TITLE
Possible built in checklist items

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-panel-checklists#9]
### Environment

- [ ] Protected the content folder
- [ ] Kirby version up to date
- [ ] Apache version
- [ ] PHP version

### SEO

- [ ] Seo title tag
- [ ] Seo meta description
